### ISSUE TITLE
Card not showing

### ISSUE THREAD

**Issue by Kateriine** [ljmerza/light-entity-card#124]
![img 2024-02-12 à 09 27 00](https://github.com/ljmerza/light-entity-card/assets/2129638/dd693e5c-4237-478f-bb5d-0a0754d15599)
On Chrome 121.0.6167.160 , with HA latest versions, and card 6.1.3, shadowRoot is empty, so it's giving some errors:

> Uncaught TypeError: Cannot read properties of null (reading 'offsetWidth')
>     at hi.getColorPickerWidth (index.js:81:48)
>     at hi.setColorWheels (index.js:54:35)
>     at index.js:233:12

**In index.js:**

```
const elem = this.shadowRoot.querySelector('.light-entity-card');
const width = elem.offsetWidth;
```
_______
>   reactive-element.js:6 Uncaught (in promise) TypeError: (intermediate value)(intermediate value)(intermediate value).importNode is not a function
>     at t.value (lit-html.ts:1122:52)
>     at t.value (lit-html.ts:1528:33)
>     at t.value (lit-html.ts:1375:12)
>     at lit-html.ts:2169:8
>     at hi.value (lit-element.ts:165:24)
>     at hi.performUpdate (reactive-element.js:6:4849)
>     at hi.scheduleUpdate (reactive-element.js:6:4496)
>     at hi._$Ej (reactive-element.js:6:4404)

**In lit.html.ts:**
`const fragment = (options?.creationScope ?? d).importNode(content, true);`

**Comment by stevemutch** [comment]
I have the same issue. TypeError: Cannot read properties of null (reading 'offsetWidth') hi.getColorPickerWidth (/hacsfiles/light-entity-card/light-entity-card.js:365:1506) hi.setColorWheels (/hacsfiles/light-entity-card/light-entity-card.js:365:1021) /hacsfiles/light-entity-card/light-entity-card.js:370:399

**Comment by akowalski** [comment]
Hi, I have the same issue, while in Firefox and HA companion app it renders fine.
